Quando foi a última vez que você fez algo pela primeira vez? (Cesar Curti)
EAT clean. DRINK water. STAY active. BE healthy. (Unknown)
Nunca sacrifique essas trás coisas: Sua família. Sua saúde. E sua dignidade. (Unknown)
Buda não era Budista. Cristo não era Cristão. Maomé não era mulçumano. Eles eram Mestres que ensinavam amor. Amor era sua religião. (Unknown)
Você atrai o que transmite. (Unknown)
A única coisa fixa é que tudo está em constante transformação, Aproveite o agora! (Thalita Froes)
Regra básica da vida: na volta a descida vira subida. (Unknown)
Não importa como, mas mexa-se. (Unknown)
Opte por aquilo que faz seu coração vibrar... Apesar de todas consequencias. (Osho)
O primeiro passo para se ter um bom dia: Dê bom dia a alguém! (Unknown)